# -*- coding: utf-8 -*-
"""guess_the_number_modified.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5X2bs5LLByk5Qu4LpYN8bQBVyXU_7xA
"""

import random # With this code we can import a random number
number= random.randint(1,100) # This code creates a variable and then puts a random number between 1 and 100
print("Guess the number")
guesscount= int(0) # This is implies to how many times you have guesses. It'll be necessary to keep track of the guess limit
while guesscount < 6: # Until the times you have guesses exceed 6 the codes below will repeat
 yourguess= int(input()) # This code takes the keyboard inout of your answer and then puts into a variable
 guesscount= guesscount + 1 # We add 1 to the times you have guessed
 if yourguess == number: # If you get the number right, this code will activate. If you did not get it right, it'll switch onto the next code
   print("gg")
   break # This stops your loop
 elif number > yourguess: # If your the number you have guessed is smaller than the random number the computer has picked then this line is going to activate
   if guesscount == 6: # This code is used to check the numbers of times you have guesses through the program. This program only activates if you have lost the game by running out of guesses
     print("You lost :(") 
     print("The number was: " + number) # Shows you the random number
     break 
   else: 
     print("My number is bigger") # Used to help you get closer to the random number :)
 else:
   if guesscount == 6: # Same usage of the other one
     print("You lost :(")
     print("The number was: " + number)
     break
   else: 
     print("My number is smaller")